Repository Iduk-Baduk/itseats-web-owner, pull requests merged in 2025-06, with the labels that each got.

#2 [Feature] 가맹점 프론트 기본 레이아웃 구현
  src/App.jsx
  src/components/basic/CheckBox.jsx
  src/components/basic/CheckBox.module.css
  src/components/basic/ComboBox.jsx
  src/components/basic/ComboBox.module.css
  src/components/basic/RadioButton.jsx
  src/components/basic/RadioButton.module.css
  src/components/basic/TextInput.jsx
  src/components/basic/TextInput.module.css
  src/components/basic/UpperTextInput.jsx
  src/components/basic/UpperTextInput.module.css
  src/components/common/Header.jsx
  src/components/common/Header.module.css
  src/components/common/NavBar.jsx
  src/components/common/NavBar.module.css
  src/components/common/PosHeader.jsx
  src/components/common/PosHeader.module.css
  src/layouts/Layout.jsx
  src/layouts/Layout.module.css
  src/layouts/PosLayout.jsx
  src/layouts/PosLayout.module.css
  src/main.jsx
  src/pages/accounts/Accounts.jsx
  src/pages/accounts/Accounts.module.css
  src/pages/menus/Menus.jsx
  src/pages/menus/Menus.module.css
  src/pages/pos/POS.jsx
  src/pages/pos/PosOrders.jsx
  src/pages/reviews/Reviews.jsx
  src/pages/reviews/Reviews.module.css
  src/pages/sales/Sales.jsx
  src/pages/sales/Sales.module.css
  src/pages/settlements/Settlements.jsx
  src/pages/settlements/Settlements.module.css
  src/pages/stores/Stores.jsx
  src/pages/stores/Stores.module.css
  src/pages/users/Login.jsx
  src/pages/users/Register.jsx
  src/variables.css
Labels: feature

#4 [Feature] pos UI 구현
  package-lock.json
  package.json
  src/Store.js
  src/components/common/PosSelectModal.jsx
  src/components/common/PosSelectModal.module.css
  src/components/pos/PosMetricItem.jsx
  src/components/pos/PosMetricItem.module.css
  src/components/pos/PosOrderCard.jsx
  src/components/pos/PosOrderCard.module.css
  src/components/pos/PosOrderDetailModal.jsx
  src/components/pos/PosOrderDetailModal.module.css
  src/components/pos/PosQuickAccess.jsx
  src/components/pos/PosQuickAccess.module.css
  src/components/pos/PosSideBar.jsx
  src/components/pos/PosSideBar.module.css
  src/layouts/PosLayout.jsx
  src/main.jsx
  src/pages/pos/POS.jsx
  src/pages/pos/POS.module.css
  src/pages/pos/PosOrders.jsx
  src/pages/pos/PosOrders.module.css
  src/store/orderSlice.js
  src/variables.css
Labels: feature

#7 [Feature] 사용자 로그인/ 회원가입 UI 개발
  src/App.jsx
  src/components/basic/Button.jsx
  src/components/basic/Button.module.css
  src/components/register/Stepper.jsx
  src/components/register/Stepper.module.css
  src/constants/formFields.js
  src/pages/users/Login.jsx
  src/pages/users/Login.module.css
  src/pages/users/Register.jsx
  src/pages/users/register/RegisterCompleted.jsx
  src/pages/users/register/RegisterCompleted.module.css
  src/pages/users/register/RegisterContainer.jsx
  src/pages/users/register/RegisterStepOneUserInfo.jsx
  src/pages/users/register/RegisterStepOneUserInfo.module.css
  src/pages/users/register/RegisterStepThreeBizInfo.jsx
  src/pages/users/register/RegisterStepThreeBizInfo.module.css
  src/pages/users/register/RegisterStepTwoStoreInfo.jsx
  src/pages/users/register/RegisterStepTwoStoreInfo.module.css
  src/variables.css
Labels: feature

#8 [Feature] 메뉴 관리 UI 구현
  data/db.json
  package-lock.json
  package.json
  src/App.jsx
  src/Store.js
  src/components/common/Icons.jsx
  src/components/menu/MenuActions.jsx
  src/components/menu/MenuActions.module.css
  src/components/menu/MenuGroupModal.jsx
  src/components/menu/MenuGroupModal.module.css
  src/components/menu/MenuInput.jsx
  src/components/menu/MenuInput.module.css
  src/components/menu/MenuList.jsx
  src/components/menu/MenuList.module.css
  src/components/menu/MenuOptionGroupModal.jsx
  src/components/menu/MenuOptionGroupModal.module.css
  src/components/menu/MenuStore.jsx
  src/components/menu/MenuStore.module.css
  src/components/menu/MenuSummaryCard.jsx
  src/components/menu/MenuSummaryCard.module.css
  src/config/api.js
  src/hooks/useFetchMenus.js
  src/pages/menus/Menus.jsx
  src/pages/menus/Menus.module.css
  src/pages/menus/MenusAdd.jsx
  src/pages/menus/MenusAdd.module.css
  src/services/apiClient.js
  src/services/menuAPI.js
  src/store/menuSlice.js
  src/utils/groupMenus.js
  src/variables.css
Labels: feature

#10 Feat/#9-menu-crud-UI
  data/db.json
  package-lock.json
  package.json
  src/App.jsx
  src/components/common/Icons.jsx
  src/components/menu/MenuActions.jsx
  src/components/menu/MenuActions.module.css
  src/components/menu/MenuGroupModal.jsx
  src/components/menu/MenuGroupModal.module.css
  src/components/menu/MenuInput.jsx
  src/components/menu/MenuInput.module.css
  src/components/menu/MenuList.jsx
  src/components/menu/MenuList.module.css
  src/components/menu/MenuOptionGroupModal.jsx
  src/components/menu/MenuOptionGroupModal.module.css
  src/components/menu/MenuSummaryCard.jsx
  src/components/menu/SortableGroupItem.jsx
  src/components/menu/SortableOptionGroup.jsx
  src/components/pos/PosQuickAccess.jsx
  src/config/api.js
  src/index.css
  src/pages/menus/Menus.jsx
  src/pages/menus/MenusAdd.jsx
  src/pages/menus/MenusAdd.module.css
  src/services/menuAPI.js
  src/store/menuSlice.js
Labels: feature, refactor

#15 Feat/#10 pos status management
  PosStatusHistory_테스트_문제해결_가이드.md
  babel.config.js
  data/db.json
  jest.config.js
  jest.setup.js
  package-lock.json
  package.json
  src/components/pos/PosAutoSettings.jsx
  src/components/pos/PosAutoSettings.module.css
  src/components/pos/PosStatusBadge.jsx
  src/components/pos/PosStatusBadge.module.css
  src/components/pos/PosStatusControl.jsx
  src/components/pos/PosStatusControl.module.css
  src/components/pos/PosStatusHistory.jsx
  src/components/pos/PosStatusHistory.module.css
  src/components/pos/__tests__/PosIntegration.test.jsx
  src/components/pos/__tests__/PosStatusBadge.test.jsx
  src/components/pos/__tests__/PosStatusControl.test.jsx
  src/components/pos/__tests__/PosStatusHistory.test.jsx
  src/config/api.js
  src/constants/posStatus.js
  src/hooks/usePosAutoScheduler.js
  src/pages/pos/POS.jsx
  src/pages/pos/POS.module.css
  src/services/posAPI.js
  src/utils/__tests__/errorHandler.test.js
  src/utils/__tests__/posAutoScheduler.test.js
  src/utils/errorHandler.js
  src/utils/posAutoScheduler.js
  vite.config.js
Labels: enhancement, feature, refactor
